### ISSUE TITLE
Error parsing command line: unrecognised option '--rest'

### ISSUE THREAD

**Issue by Bilal112** [bradtraversy/nodekb#4]
Error parsing command line: unrecognised option '--rest'
how cansolve this error

**Comment by salahgafoor** [comment]
If the issue is related with mongodb,

The --rest parameter was removed in MongoDB 3.6 as described in this page: [MongoDB Configuration Hardening](https://docs.mongodb.com/manual/core/security-mongodb-configuration/)

Remove the --rest option from your command line.
